pipeline:
  clone:
    image: plugins/git
    tags: true

  build:
    image: python:3
    commands:
      - python setup.py bdist_wheel
      - python setup.py test

  publish:
    image: plugins/drone-devpi
    devpi:
      server: http://192.168.0.40:3141/
      index: dietzi/stable
      username: dietzi
      password: dietzi